# Generated by Django 4.2.10 on 2024-02-10 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_contact_tag_organization_event_contact_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contacts",
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(blank=True, related_name="events", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contacts",
            field=models.ManyToManyField(blank=True, related_name="contacts", to="users.contact"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="contacts", to="users.tag"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="info", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="users.contact"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="users.organization",
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="announcements", to="users.tag")),
            ],
        ),
    ]
